name: ci

on:
  release:
    types: [published]
    tag:
    - v1.*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yeemonaung286/randnumimg:v1.0

      -
        name: Post message on slack
        uses: bluenovaio/action-slack@main
        with:
          username: "Yeemonaung1"
          icon_emoji: ":robot_face:"
          text:  "Name: Yee Mon Aung \nMatriculation: A0249475N \nEmail: <outlook.com|E0941668@u.nus.edu> \nRepo: <https://https://github.com/Yeemonaung1/randnum.git|git://github.com/Yeemonaung1/randnum.git>\nImage name: yeemonaung286/randnumimg:${{github.ref_name}}\nImage url: <https://hub.docker.com/repository/docker/yeemonaung286/randnumimg|https://hub.docker.com/repository/docker/yeemonaung286/randnumimg>"

          webhook_url: ${{ secrets.SLACK_WEBHOOK }}